
CREATE TABLE FILMES (
                FILME_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT FILMES_PK PRIMARY KEY (FILME_PK)
);


CREATE TABLE SALAS (
                SALA_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT SALA_PK PRIMARY KEY (SALA_PK)
);


CREATE TABLE DIRETORES (
                DIRETOR_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT DIRETOR_PK PRIMARY KEY (DIRETOR_PK)
);


CREATE TABLE GENEROS (
                GENERO_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT GENERO_PK PRIMARY KEY (GENERO_PK)
);


CREATE TABLE REGIOES (
                REGIAO_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT REGIOES_PK PRIMARY KEY (REGIAO_PK)
);


CREATE TABLE SESSOES (
                SESSAO_PK NUMBER NOT NULL,
                HORARIO DATE NOT NULL,
                CONSTRAINT SESSAO_PK PRIMARY KEY (SESSAO_PK)
);


CREATE TABLE PAISES (
                PAIS_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT PAIS_PK PRIMARY KEY (PAIS_PK)
);


CREATE TABLE ATORES (
                ATOR_PK NUMBER NOT NULL,
                NOME VARCHAR2(255) NOT NULL,
                CONSTRAINT ATORES_PK PRIMARY KEY (ATOR_PK)
);


CREATE TABLE DISTRIBUIDORAS (
                DISTRIBUIDORA_ATOR_PK NUMBER NOT NULL,
                DISTRIBUIDORA_PAIS_PK NUMBER NOT NULL,
                DISTRIBUIDORA_REGIAO_PK NUMBER NOT NULL,
                DISTRIBUIDORA_GENERO_PK NUMBER NOT NULL,
                DISTRIBUIDORA_SESSAO_PK NUMBER NOT NULL,
                DISTRIBUIDORA_DIRETOR_PK NUMBER NOT NULL,
                DISTRIBUIDORA_SALA_PK NUMBER NOT NULL,
                DISTRIBUIDORA_FILME_PK NUMBER NOT NULL,
                PUBLICO_TOTAL NUMBER NOT NULL,
                VALOR_ARRECADADO NUMBER(15,2) NOT NULL,
                CAPACIDADE NUMBER NOT NULL,
                CONSTRAINT DISTRIBUIDORA_PK PRIMARY KEY (DISTRIBUIDORA_ATOR_PK, DISTRIBUIDORA_PAIS_PK, DISTRIBUIDORA_REGIAO_PK, DISTRIBUIDORA_GENERO_PK, DISTRIBUIDORA_SESSAO_PK, DISTRIBUIDORA_DIRETOR_PK, DISTRIBUIDORA_SALA_PK, DISTRIBUIDORA_FILME_PK)
);


ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT FILMES_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_FILME_PK)
REFERENCES FILMES (FILME_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT SALAS_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_SALA_PK)
REFERENCES SALAS (SALA_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT DIRETORES_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_DIRETOR_PK)
REFERENCES DIRETORES (DIRETOR_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT GENEROS_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_GENERO_PK)
REFERENCES GENEROS (GENERO_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT REGIOES_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_REGIAO_PK)
REFERENCES REGIOES (REGIAO_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT SESSOES_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_SESSAO_PK)
REFERENCES SESSOES (SESSAO_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT PAISES_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_PAIS_PK)
REFERENCES PAISES (PAIS_PK)
NOT DEFERRABLE;

ALTER TABLE DISTRIBUIDORAS ADD CONSTRAINT ATORES_DISTRIBUIDORAS_FK
FOREIGN KEY (DISTRIBUIDORA_ATOR_PK)
REFERENCES ATORES (ATOR_PK)
NOT DEFERRABLE;
